# Generated by Django 5.2.1 on 2025-06-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahara_webapp', '0002_categorie_client_fournisseur_produitimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'managed': True},
        ),
    ]
