# Generated by Django 5.2.1 on 2025-06-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahara_webapp', '0003_alter_fournisseur_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fournisseur',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
