# Generated by Django 5.2.1 on 2025-06-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahara_webapp', '0004_fournisseur_description_fournisseur_site_web_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'managed': False},
        ),
    ]
