# Generated by Django 5.2.1 on 2025-06-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sahara_webapp', '0005_alter_fournisseur_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'managed': True},
        ),
    ]
