# Generated by Django 5.2.1 on 2025-06-05 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sahara_webapp', '0007_alter_fournisseur_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('valide', 'Validé'), ('refuse', 'Refusé')], max_length=10)),
                ('date_decision', models.DateTimeField(auto_now_add=True)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('fournisseur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sahara_webapp.fournisseur')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'validation_fournisseur',
            },
        ),
    ]
